# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
# Site
title: 戚旗Blog 
subtitle: Coding like a DREAMER
description: 戚旗Blog (Tim Qi)
author: Qi (Tim) Qi, 戚旗
beian: 京ICP备15052297号-1
record:
language:
timezone:
i_host: https://cdn.jsdelivr.net/gh/timqi/Blog@gh-pages/i/

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.timqi.com/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: other
ategory_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

include:
  - .nojekyll
exclude:
  - .gitignore
  - README.md

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

archive_generator:
  per_page: 30
  yearly: true 
  monthly: true
  daily: false

category_generator:
  per_page: 30

tag_generator:
  per_page: 30

feed:
  type: atom
  path: atom.xml
  limit: 20
  content: true

theme: bootstrap-blog
disqus_shortname: timqisblog

deploy:
  type: git
  repo: git@github.com:timqi/Blog.git
  branch: gh-pages
